name: adaptive_widgeet
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.11.5







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  fl_chart: ^1.2.0
  cached_network_image: ^3.4.1
  http: ^1.6.0
  get: ^4.7.3
  provider: ^6.1.5+1
  image_picker: ^1.2.2
  graphic: ^2.7.0
  intl: ^0.20.2
  quiver: ^3.2.2
  dio: ^5.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^6.0.0





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
